/**
 * Phase 4 -- real-time dashboard + LiveState integration.
 *
 * Renders the real <App/> against real captured / real-generated wire payloads (Scenario-08 sim
 * frames from `test/fixtures.ts`, plus `REAL_HARDWARE_FRAME_MESSAGE` generated by driving an
 * actual STM32ProcessedFrame through the Phase-3 ESP32 path). Nothing is mocked except the
 * WebSocket and `fetch`. Every assertion checks a value that came straight off `PerceptionFrameData`
 * or `GET /debug/stream-status`, never a client-side calculation.
 *
 * Covers §21 cases: empty state, single/multiple objects, track update, object disappearance,
 * TTC/clearance/risk update, session change, sequence change, stale frame, connection loss,
 * WebSocket reconnect, hardware-data-unavailable, simulation mode, hardware/mock mode, dashboard
 * state consistency, Unity state consistency.
 */
import { act, render, screen, waitFor, within } from "@testing-library/react";
import { beforeEach, afterEach, describe, expect, it, vi } from "vitest";
import App from "./App";
import { MockWebSocket } from "./test/mockWebSocket";
import type { LiveMessage } from "./types";
import {
  REAL_CRITICAL_FRAME_MESSAGE,
  REAL_NEXT_CRITICAL_FRAME_MESSAGE,
  REAL_SCENARIO_SWITCH_FRAME_MESSAGE,
  REAL_HARDWARE_FRAME_MESSAGE,
  HARDWARE_UNAVAILABLE_STREAM_STATUS,
} from "./test/fixtures";

type FrameMsg = Extract<LiveMessage, { type: "frame" }>;
const CRIT = REAL_CRITICAL_FRAME_MESSAGE as FrameMsg;
const HW = REAL_HARDWARE_FRAME_MESSAGE as FrameMsg;

function stubFetchWith(streamStatus: unknown) {
  vi.stubGlobal(
    "fetch",
    vi.fn(async (url: string) => {
      if (url.includes("/debug/stream-status")) {
        return { ok: true, status: 200, json: async () => streamStatus } as Response;
      }
      return { ok: true, status: 200, json: async () => [] } as Response;
    }),
  );
}

beforeEach(() => {
  MockWebSocket.reset();
  vi.stubGlobal("WebSocket", MockWebSocket as unknown as typeof WebSocket);
  vi.stubGlobal("fetch", vi.fn(() => Promise.reject(new Error("fetch not mocked for this test"))));
});

afterEach(() => {
  vi.unstubAllGlobals();
  vi.useRealTimers();
});

// ------------------------------------------------------------------------------------------
// §21.1 empty state
// ------------------------------------------------------------------------------------------

describe("empty state -- nothing fabricated before data arrives", () => {
  it("Objects=0, Tracks=0, Risk=—, NO ACTIVE OBJECTS, System DISCONNECTED", () => {
    render(<App />);
    const objectsPanel = screen.getByTestId("objects-panel");
    expect(within(objectsPanel).getByText("Object Count").closest(".stat-tile")!.textContent).toContain("0");
    expect(within(objectsPanel).getByText("Track Count").closest(".stat-tile")!.textContent).toContain("0");
    expect(within(screen.getByTestId("safety-panel")).getByText("Risk").closest(".stat-tile")!.textContent).toContain("—");
    expect(within(screen.getByTestId("tracked-objects-table")).getByText("NO ACTIVE OBJECTS")).toBeInTheDocument();
    expect(within(screen.getByTestId("system-status-panel")).getByText(/System: DISCONNECTED/)).toBeInTheDocument();
  });
});

// ------------------------------------------------------------------------------------------
// §21.2/3 single / multiple objects, §21.10 sequence change
// ------------------------------------------------------------------------------------------

describe("object rendering from LiveState", () => {
  it("single object: table row + counts come from tracked_objects, not recomputed", async () => {
    render(<App />);
    const socket = MockWebSocket.latest();
    act(() => socket.emitOpen());
    act(() => socket.emitMessage(REAL_CRITICAL_FRAME_MESSAGE));

    const table = screen.getByTestId("tracked-objects-table");
    await waitFor(() => expect(within(table).getByText("#track-1")).toBeInTheDocument());
    expect(within(table).getByText("vehicle like")).toBeInTheDocument();
    expect(within(table).getByText("5.2 m")).toBeInTheDocument(); // distance, verbatim
    expect(within(table).getByText("0.9 s")).toBeInTheDocument(); // TTC, joined at the Edge
    const objectsPanel = screen.getByTestId("objects-panel");
    expect(within(objectsPanel).getByText("Object Count").closest(".stat-tile")!.textContent).toContain("1");
  });

  it("multiple objects: two rows, two distinct track ids", async () => {
    render(<App />);
    const socket = MockWebSocket.latest();
    act(() => socket.emitOpen());
    act(() => socket.emitMessage(REAL_SCENARIO_SWITCH_FRAME_MESSAGE)); // 05_multiple_obstacles: track-1 + track-9

    const table = screen.getByTestId("tracked-objects-table");
    await waitFor(() => expect(within(table).getByText("#track-1")).toBeInTheDocument());
    expect(within(table).getByText("#track-9")).toBeInTheDocument();
    expect(within(table).getByText("wall")).toBeInTheDocument();
    expect(within(table).getByText("pole like")).toBeInTheDocument();
    expect(within(screen.getByTestId("objects-panel")).getByText("Track Count").closest(".stat-tile")!.textContent).toContain("2");
  });

  it("sequence change: a newer frame_id replaces the old one, values move", async () => {
    render(<App />);
    const socket = MockWebSocket.latest();
    act(() => socket.emitOpen());
    act(() => socket.emitMessage(REAL_CRITICAL_FRAME_MESSAGE)); // seq 13
    const liveData = screen.getByTestId("live-data-panel");
    await waitFor(() => expect(within(liveData).getByText("#13")).toBeInTheDocument());
    act(() => socket.emitMessage(REAL_NEXT_CRITICAL_FRAME_MESSAGE)); // seq 14
    await waitFor(() => expect(within(liveData).getByText("#14")).toBeInTheDocument());
    expect(within(liveData).queryByText("#13")).not.toBeInTheDocument();
  });
});

// ------------------------------------------------------------------------------------------
// §21.5 object disappearance -- no stale objects retained
// ------------------------------------------------------------------------------------------

describe("object disappearance -- objects are never retained from a previous frame", () => {
  it("a later frame with zero objects clears the table", async () => {
    render(<App />);
    const socket = MockWebSocket.latest();
    act(() => socket.emitOpen());
    act(() => socket.emitMessage(REAL_CRITICAL_FRAME_MESSAGE));
    const table = screen.getByTestId("tracked-objects-table");
    await waitFor(() => expect(within(table).getByText("#track-1")).toBeInTheDocument());

    // same session, next sequence, but no objects this scan
    const emptyFrame = {
      ...CRIT,
      frame_id: 20,
      data: {
        ...CRIT.data,
        sequence_number: 20,
        objects: [],
        tracked_objects: [],
        risk: { overall_risk: "safe" as const, most_critical: null, results: [] },
      },
    };
    act(() => socket.emitMessage(emptyFrame));
    await waitFor(() => expect(within(table).getByText("NO ACTIVE OBJECTS")).toBeInTheDocument());
    expect(within(table).queryByText("#track-1")).not.toBeInTheDocument();
    expect(within(screen.getByTestId("safety-panel")).getByText("Risk").closest(".stat-tile")!.textContent).toContain("SAFE");
  });
});

// ------------------------------------------------------------------------------------------
// §21.6/7/8 TTC / clearance / risk update
// ------------------------------------------------------------------------------------------

describe("TTC / clearance / risk are displayed verbatim and update per frame", () => {
  it("risk SAFE -> CRITICAL, TTC N/A -> finite, clearance numbers move", async () => {
    render(<App />);
    const socket = MockWebSocket.latest();
    act(() => socket.emitOpen());

    // start from the scenario-switch frame (SAFE, no results -> Min TTC N/A)
    act(() => socket.emitMessage(REAL_SCENARIO_SWITCH_FRAME_MESSAGE));
    const safety = screen.getByTestId("safety-panel");
    await waitFor(() => expect(within(safety).getByText("SAFE")).toBeInTheDocument());
    expect(within(safety).getByText("Min TTC", { selector: ".stat-label" }).closest(".stat-tile")!.textContent).toContain("N/A");

    // ...then a CRITICAL frame with a finite TTC (different session -> full reset, fine)
    act(() => socket.emitMessage(REAL_CRITICAL_FRAME_MESSAGE));
    await waitFor(() => expect(within(safety).getByText("CRITICAL")).toBeInTheDocument());
    expect(within(safety).getByText("Min TTC", { selector: ".stat-label" }).closest(".stat-tile")!.textContent).toContain("0.9 s");
    expect(screen.getByText("1.89 m")).toBeInTheDocument(); // front clearance, verbatim

    act(() => socket.emitMessage(REAL_NEXT_CRITICAL_FRAME_MESSAGE));
    await waitFor(() => expect(screen.getByText("1.69 m")).toBeInTheDocument()); // clearance moved
    expect(screen.queryByText("1.89 m")).not.toBeInTheDocument();
  });

  it("no distance-based risk in the frontend: a close object with SAFE risk on the wire renders SAFE", async () => {
    render(<App />);
    const socket = MockWebSocket.latest();
    act(() => socket.emitOpen());
    // object at 1.0 m but the Edge said SAFE -- the dashboard must trust the wire, not distance.
    const closeButSafe = {
      ...CRIT,
      frame_id: 30,
      data: {
        ...CRIT.data,
        sequence_number: 30,
        objects: [{ ...CRIT.data.objects[0], centroid: { x: 1.0, y: 0 }, distance: 1.0 }],
        tracked_objects: [{ ...CRIT.data.tracked_objects![0], x: 1.0, distance: 1.0, risk: "safe" as const, ttc: null }],
        risk: { overall_risk: "safe" as const, most_critical: null, results: [] },
      },
    };
    act(() => socket.emitMessage(closeButSafe));
    const table = screen.getByTestId("tracked-objects-table");
    await waitFor(() => expect(within(table).getByText("1.0 m")).toBeInTheDocument());
    expect(within(table).getByText("safe")).toBeInTheDocument(); // risk badge from the wire
    expect(within(table).getByText("N/A")).toBeInTheDocument(); // TTC null -> N/A, never fabricated
  });
});

// ------------------------------------------------------------------------------------------
// §21.9 session change -- old objects / risk / TTC gone
// ------------------------------------------------------------------------------------------

describe("session change -- the dashboard immediately reflects the new session", () => {
  it("01-like -> 05-like: old track/risk/trajectory gone, new ones shown", async () => {
    render(<App />);
    const socket = MockWebSocket.latest();
    act(() => socket.emitOpen());
    act(() => socket.emitMessage(REAL_CRITICAL_FRAME_MESSAGE)); // session 08, CRITICAL, track-1 @ x=5.15
    const historyPanel = screen.getByTestId("tracking-history-panel");
    await waitFor(() => expect(within(historyPanel).getByText(/x=5\.15/)).toBeInTheDocument());
    expect(within(screen.getByTestId("safety-panel")).getByText("CRITICAL")).toBeInTheDocument();

    act(() => socket.emitMessage(REAL_SCENARIO_SWITCH_FRAME_MESSAGE)); // session 05, SAFE, track-1 @ x=9.0
    await waitFor(() => expect(within(historyPanel).getByText(/x=9\.00/)).toBeInTheDocument());
    expect(within(historyPanel).queryByText(/x=5\.15/)).not.toBeInTheDocument(); // old trajectory gone
    expect(within(screen.getByTestId("safety-panel")).getByText("SAFE")).toBeInTheDocument(); // old CRITICAL gone
    expect(screen.getByText(/Scenario: simulated:05_multiple_obstacles/)).toBeInTheDocument();
  });
});

// ------------------------------------------------------------------------------------------
// §21.11 stale frame  /  §21.12 connection loss  /  §21.13 WS reconnect
// ------------------------------------------------------------------------------------------

describe("stale / disconnected -- never looks live when no data is arriving", () => {
  it("goes STALE DATA after the threshold with the socket still open", async () => {
    vi.useFakeTimers();
    render(<App />);
    const socket = MockWebSocket.latest();
    act(() => socket.emitOpen());
    act(() => socket.emitMessage(REAL_CRITICAL_FRAME_MESSAGE));
    const panel = screen.getByTestId("system-status-panel");
    expect(within(panel).getByText(/System: LIVE/)).toBeInTheDocument();
    act(() => vi.advanceTimersByTime(4000));
    expect(within(panel).getByText(/System: STALE DATA/)).toBeInTheDocument();
  });

  it("connection loss: socket closes -> System DISCONNECTED, and a reconnect socket is created (exactly one)", () => {
    vi.useFakeTimers();
    render(<App />);
    const first = MockWebSocket.latest();
    act(() => first.emitOpen());
    act(() => first.emitMessage(REAL_CRITICAL_FRAME_MESSAGE));
    expect(within(screen.getByTestId("system-status-panel")).getByText(/System: LIVE/)).toBeInTheDocument();

    const before = MockWebSocket.instances.length;
    act(() => first.close());
    expect(within(screen.getByTestId("system-status-panel")).getByText(/System: DISCONNECTED/)).toBeInTheDocument();

    act(() => vi.advanceTimersByTime(2000)); // RECONNECT_DELAY_MS
    expect(MockWebSocket.instances.length).toBe(before + 1); // exactly one new socket, not a storm
    act(() => vi.advanceTimersByTime(6000));
    expect(MockWebSocket.instances.length).toBe(before + 1); // still just one -- no accidental duplicates
  });
});

// ------------------------------------------------------------------------------------------
// §21.14 hardware data unavailable  /  §21.16 hardware / mock ESP32 mode  /  §18
// ------------------------------------------------------------------------------------------

describe("hardware mode", () => {
  it("renders a real hardware-source frame: Mode HARDWARE, source stm32_hardware, fused sensor source", async () => {
    stubFetchWith(HARDWARE_UNAVAILABLE_STREAM_STATUS); // any stream-status; the frame drives the panels
    render(<App />);
    const socket = MockWebSocket.latest();
    act(() => socket.emitOpen());
    act(() => socket.emitMessage(REAL_HARDWARE_FRAME_MESSAGE));

    await waitFor(() =>
      expect(within(screen.getByTestId("data-source-panel")).getByText("HARDWARE")).toBeInTheDocument(),
    );
    expect(within(screen.getByTestId("data-source-panel")).getByText("stm32_hardware")).toBeInTheDocument();

    const table = screen.getByTestId("tracked-objects-table");
    expect(within(table).getByText("#stm32-track-1")).toBeInTheDocument();
    expect(within(table).getByText("vehicle like")).toBeInTheDocument();
    expect(within(table).getByText("lidar+radar")).toBeInTheDocument(); // real fusion attribution
    expect(within(table).getByText("6.0 m")).toBeInTheDocument();
    expect(within(table).getByText("3.0 s")).toBeInTheDocument(); // TTC from the processed frame
    expect(within(screen.getByTestId("safety-panel")).getByText("WARNING")).toBeInTheDocument();
  });

  it("HARDWARE DATA UNAVAILABLE banner appears from /debug/stream-status last_error_code -- no auto sim fallback", async () => {
    stubFetchWith(HARDWARE_UNAVAILABLE_STREAM_STATUS);
    render(<App />);
    const socket = MockWebSocket.latest();
    act(() => socket.emitOpen());

    await waitFor(() =>
      expect(screen.getByTestId("hardware-unavailable").textContent).toMatch(/HARDWARE DATA UNAVAILABLE/),
    );
    expect(screen.getByTestId("hardware-unavailable").textContent).toContain("stale data");
    // the dashboard shows NO objects -- it did not invent any / fall back to simulation
    expect(within(screen.getByTestId("tracked-objects-table")).getByText("NO ACTIVE OBJECTS")).toBeInTheDocument();
    expect(within(screen.getByTestId("system-status-panel")).getByText(/ESP32: UNAVAILABLE/)).toBeInTheDocument();
  });
});

// ------------------------------------------------------------------------------------------
// §21.15 simulation mode unaffected
// ------------------------------------------------------------------------------------------

describe("simulation mode is unaffected", () => {
  it("a sim frame shows Mode SIMULATION and the scenario source id", async () => {
    render(<App />);
    const socket = MockWebSocket.latest();
    act(() => socket.emitOpen());
    act(() => socket.emitMessage(REAL_CRITICAL_FRAME_MESSAGE));
    await waitFor(() =>
      expect(within(screen.getByTestId("data-source-panel")).getByText("SIMULATION")).toBeInTheDocument(),
    );
    expect(within(screen.getByTestId("data-source-panel")).getByText("simulated:08_approaching_obstacle")).toBeInTheDocument();
    // no ESP32 badge / no hardware-unavailable banner in sim mode
    expect(screen.queryByTestId("hardware-unavailable")).not.toBeInTheDocument();
    expect(within(screen.getByTestId("system-status-panel")).queryByText(/ESP32:/)).not.toBeInTheDocument();
  });
});

// ------------------------------------------------------------------------------------------
// §21.17 dashboard state consistency  /  §21.18 Unity state consistency
// ------------------------------------------------------------------------------------------

describe("state consistency", () => {
  it("dashboard panels agree with each other on the same frame's values", async () => {
    render(<App />);
    const socket = MockWebSocket.latest();
    act(() => socket.emitOpen());
    act(() => socket.emitMessage(REAL_CRITICAL_FRAME_MESSAGE));

    const table = screen.getByTestId("tracked-objects-table");
    await waitFor(() => expect(within(table).getByText("#track-1")).toBeInTheDocument());
    // Detected Objects TTC, Safety Min TTC, and the Critical Object breakdown all read the SAME
    // wire value (0.8758 -> "0.9 s") -- no panel recomputes it.
    expect(within(table).getByText("0.9 s")).toBeInTheDocument();
    const safety = screen.getByTestId("safety-panel");
    expect(within(safety).getByText("Min TTC", { selector: ".stat-label" }).closest(".stat-tile")!.textContent).toContain("0.9 s");
    expect(within(safety).getByText(/TTC: 0.9 s/)).toBeInTheDocument();
  });

  it("Unity consistency: the wire fields Unity parses equal the ones the dashboard shows (same message)", () => {
    // Dashboard and Unity are independent TCP clients of the SAME PerceptionStreamServer.publish()
    // output. This asserts the single wire message carries ONE consistent value per field, so
    // "Dashboard track_id == Unity track_id" etc. holds by construction (Unity does no perception).
    const d = HW.data;
    const obj = d.objects[0];
    const tracked = d.tracked_objects![0];
    const result = d.risk!.results[0];
    expect(tracked.track_id).toBe(obj.track_id);
    expect(result.track_id).toBe(obj.track_id);
    expect(tracked.classification).toBe(obj.classification);
    expect(tracked.distance).toBe(obj.distance);
    expect(tracked.ttc).toBe(result.ttc);
    expect(tracked.risk).toBe(result.risk_level);
    expect(d.risk!.overall_risk).toBe(tracked.risk);
    expect(d.clearance!.min_direction).toBe("left");
  });
});

// ------------------------------------------------------------------------------------------
// §12 update rate -- real, never a fixed constant
// ------------------------------------------------------------------------------------------

describe("update rate is measured, never a fixed constant", () => {
  it("shows the Edge measured_scan_rate_hz when present", async () => {
    render(<App />);
    const socket = MockWebSocket.latest();
    act(() => socket.emitOpen());
    act(() => socket.emitMessage(REAL_CRITICAL_FRAME_MESSAGE)); // performance_metrics.measured_scan_rate_hz = 10.0
    const liveData = screen.getByTestId("live-data-panel");
    await waitFor(() =>
      expect(within(liveData).getByText("Scan Rate").closest(".stat-tile")!.textContent).toContain("10.0 Hz"),
    );
  });

  it("falls back to this tab's own frames/elapsed when the Edge rate is absent -- not a hardcoded 10 Hz", () => {
    const nowSpy = vi.spyOn(Date, "now");
    nowSpy.mockReturnValue(1_000_000_000_000);
    render(<App />);
    const socket = MockWebSocket.latest();
    act(() => socket.emitOpen());

    const noRate = (seq: number) => ({
      ...HW,
      frame_id: seq,
      data: {
        ...HW.data,
        sequence_number: seq,
        performance_metrics: { pipeline_processing_ms: 5, measured_scan_interval_s: null, measured_scan_rate_hz: null, scans_processed: seq + 1 },
      },
    });

    nowSpy.mockReturnValue(1_000_000_000_000);
    act(() => socket.emitMessage(noRate(0)));
    nowSpy.mockReturnValue(1_000_000_000_250); // +250 ms
    act(() => socket.emitMessage(noRate(1)));
    nowSpy.mockReturnValue(1_000_000_000_500); // +250 ms -> 2 frames over 0.5 s -> 4.0 Hz
    act(() => socket.emitMessage(noRate(2)));

    const txt = within(screen.getByTestId("live-data-panel")).getByText("Scan Rate").closest(".stat-tile")!.textContent!;
    expect(txt).toMatch(/\d\.\d Hz/);        // a real measured figure
    expect(txt).not.toContain("target");     // NOT the configured-target fallback
    expect(txt).toContain("4.0 Hz");         // (count-1)/elapsed = 2 / 0.5 s
    nowSpy.mockRestore();
  });
});

// ------------------------------------------------------------------------------------------
// §14 Event Timeline -- connection events from real observed transitions
// ------------------------------------------------------------------------------------------

describe("Event Timeline includes connection events from real transitions", () => {
  it("'Data stream started' appears once a frame arrives; wire events still shown", async () => {
    render(<App />);
    const socket = MockWebSocket.latest();
    act(() => socket.emitOpen());
    act(() => socket.emitMessage(REAL_SCENARIO_SWITCH_FRAME_MESSAGE)); // carries 2 track_created events

    const timeline = screen.getByTestId("event-timeline-panel");
    await waitFor(() => expect(within(timeline).getByText(/Data stream started/)).toBeInTheDocument());
    expect(within(timeline).getAllByText(/Track Created/).length).toBeGreaterThan(0);
  });

  it("'Connection lost' appears when the socket closes", () => {
    vi.useFakeTimers();
    render(<App />);
    const socket = MockWebSocket.latest();
    act(() => socket.emitOpen());
    act(() => socket.emitMessage(REAL_CRITICAL_FRAME_MESSAGE));
    act(() => socket.close());
    const timeline = screen.getByTestId("event-timeline-panel");
    expect(within(timeline).getByText(/Connection lost/)).toBeInTheDocument();
  });
});
